### ISSUE TITLE
Windows安装器一闪而过

### ISSUE THREAD

**Issue by Mr54233** [ngd-b/rsup#1]
release里最新的installer，解压打开一闪而过，使用管理员权限打开之后
![image](https://github.com/user-attachments/assets/5db186d8-9d43-480d-8480-695b2b659579)
是这样的，下载完成之后也是会直接消失
![image](https://github.com/user-attachments/assets/8a289a9a-188f-4bdf-8dbe-767cdbc8b20e)
然后在rsup的目录下有这两个东西，rsup命令也没有生效

需要如何配置

**Comment by ngd-b** [comment]
# 手动安装

## 创建安装目录`rsup`

默认存放的目录位置 `C:\Program Files\rsup`, 位置不可更改，暂时不支持自定义其他位置存放。

## 三个资源`config.toml` - 配置；`rsup.exe` - 执行文件 ;`web` - web服务资源

在目录创建`config.toml`，写入以下内容：

```toml
name = "rsup"
version = "0.3.0"
dir = 'C:\Program Files\rsup'

[web]
port = 8888
static_dir = 'C:\Program Files\rsup/web'

[pkg]
npm_registry = "https://registry.npmmirror.com"
```

在执行`installer.exe`这个文件可以自动生成，无需更改。

### 下载 `rsup`资源包 [下载地址](https://github.com/ngd-b/rsup/releases/download/latest/rsup-windows-latest.zip)

下载压缩包，然后解压到目录`C:\Program Files\rsup` , 如果功能有更新，可有直接下载发布的新资源。

### 下载`rsup-web`资源包 [下载地址](https://github.com/ngd-b/rsup-web/releases/download/latest/rsup-web.tar.gz)

下载压缩包，然后解压到目录`C:\Program Files\rsup` , 如果功能有更新，可有直接下载发布的新资源。

解压后的文件名称为 `rsup-web` 修改为`web`

资源下载完后，目录是这样的
![image](https://github.com/user-attachments/assets/edb994d0-1e49-4842-9730-05a144083e58)

## 配置环境变量

![image](https://github.com/user-attachments/assets/c9590198-3480-4003-ab47-38f85c62c2b1)


## 打开命令行测试是否安装成功

![image](https://github.com/user-attachments/assets/cf93539f-6289-42d1-9c3c-98b006f5067f)

有版本输出，说明安装成功了。可以全局使用了，找一个前端项目有`package.json`文件，在项目目录下执行`rsup`

![image](https://github.com/user-attachments/assets/5b04752c-7713-4ae6-946c-56fc0916b56c)

服务启动成功，会自动打开浏览器，如果没有自动打开，可以手动访问服务地址

![image](https://github.com/user-attachments/assets/1df68816-3027-48a3-9c63-6f1862c3150b)

展示了`dependencies` 和`devDependencies` 依赖的最新版本信息。
